name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight (UTC) every day

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run update.sh
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          ./update.sh
